# Generated by Django 4.1 on 2023-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
