# Generated by Django 4.1 on 2023-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaPost', '0004_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
